[project]
name = "uv-fastapi-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio==4.14.0",
    "apache-airflow==3.2.0",
    "fastapi[standard]>=0.112.1",
    "glances==4.0.8",
    "jupyter_server==2.20.0"
]
